### ISSUE TITLE
Remove `DirectLink` integration, is not used anymore

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay-ingenico#15]
In our usage statistics we see that the 'DirectLink' integration is not used, so there is no added value in maintaining it anymore.

**Comment by rvdsteege** [comment]
After discussion with @remcotolsma at Pronamic HQ, I checked if the `DirectLink` integration is somehow in use for retrieval of order statuses in the `OrderStandard` integration. The request to a _direct query URL_ is in the client of the `OrderStandard` integration:

https://github.com/pronamic/wp-pronamic-pay-ingenico/blob/c430deb4f209521925170068f1bdf5fcd5443da5/src/OrderStandard/Client.php#L271-L328

The request response gets parsed through the `Pronamic\WordPress\Pay\Gateways\Ingenico\XML\OrderResponseParser` class, which in turn currently uses a `Pronamic\WordPress\Pay\Gateways\Ingenico\DirectLink\OrderResponse` class from the `DirectLink` integration. However, I think we can do without that almost empty class — used for converting a SimpleXML array to object:

https://github.com/pronamic/wp-pronamic-pay-ingenico/blob/c430deb4f209521925170068f1bdf5fcd5443da5/src/DirectLink/OrderResponse.php#L1-L45

https://github.com/pronamic/wp-pronamic-pay-ingenico/blob/c430deb4f209521925170068f1bdf5fcd5443da5/src/XML/OrderResponseParser.php#L19-L51

**Comment by rvdsteege** [comment]
ℹ️ Removed integrations from plugins:

- https://github.com/pronamic/wp-pronamic-pay/commit/5322ba9862e7af3196b8b2dda26723b953933c34
- https://github.com/pronamic/pronamic-pay-premium/commit/1fefe7f5222044688c19d62b09ea4b3b72ebe538
