### ISSUE TITLE
Add recurring payments support

### ISSUE THREAD

**Issue by rvdsteege** [pronamic/wp-pronamic-pay-ingenico#4]
We received an enquiry about support for WooCommerce Subscriptions (recurring payments) with Ingenico. Unfortunately, this is currently not supported. We might add this in the future, if there seems to be demand for this functionality.

_Internal Help Scout ticket: https://secure.helpscout.net/conversation/1993848434/24396/_

**Comment by remcotolsma** [comment]
We will not add this to this library, it seems that Worldline is moving away from the old Ogone solution:

- https://github.com/pronamic/wp-pronamic-pay-ingenico/issues/2
- https://github.com/pronamic/wp-pronamic-pay-ingenico/issues/16
