### ISSUE TITLE
Add support for iDEAL issuer ID (bank)

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay-ingenico#5]
Request of user:

> Hallo, We zien dat als we Ingenico e-commerce (OrderStandard) als betaalprovider kiezen we op het GF formulier niet de issuer kunnen kiezen. De dropdown blijft leeg (wordt bij het maken van het formulier al aangegeven). Bij Buckaroo werkt dit wel maar die provider mogen we niet gebruiken. Ik vermoed dat zij een api hebben waar deze bankenlijst kan worden opgevraagd en Ingenico dat niet heeft.Is het mogelijk of zou het mogelijk gemaakt kunnen worden om handmatig de bankenlijst toe te voegen? In bijvoorbeeld de configuratie van de betaalmethode? Of met een Wordpress hook do_action die we kunnen gebruiken om de lijst te vullen? Dan zetten we deze add_action in de functions.php of zoiets. Ik zie in de code van de plugin wel een IssuersField.php alwaar de bankenlijst zou moeten worden opgehaald maar die doet het dus met OrderStandard niet. (Met de configuratie "Ingenico DirectLink" lukt het me helemaal niet om betalingen te doen. Ik snap deze niet goed denk ik)

---

> ### 4.2 Redirect to iDEAL bank page
>
> You can also let your customer make the selection of his bank on your own check-out page, instead of on our hosted payment pages. That way we will send the customer directly to his bank's website.
> 
> To do so, you must send us the bank's ISSUERID in the hidden fields.
>
> The applicable hidden field:
>
> ```
> <input type="hidden" name="ISSUERID" value="ABNANL2A">
> ```

<img width="567" alt="Scherm­afbeelding 2023-01-16 om 15 20 17" src="https://user-images.githubusercontent.com/869674/212699882-0cd22fe2-f736-42c7-bb05-73de7e49f792.png">

https://epayments-support.ingenico.com/nl/payment-methods/alternative-payment-methods/ideal#ideal_integration_guides_integration

**Comment by remcotolsma** [comment]
We could use these unofficial API's:

- https://availability.ideal.nl/api/api/GetIssuers
- https://beschikbaarheid.ideal.nl/api/api/GetIssuers

**Comment by rvdsteege** [comment]
I prefer to not have the issuers list hard coded in the integration (or maybe only as a fall back, in case they can not be retrieved anymore from one of the open endpoints).

**Comment by remcotolsma** [comment]
I don't prefer that either, but using an unofficial API or an API from another provider is also not ideal 😏. We can also add a filter, but that is also not ideal 😏. Then users or other developers are responsible for maintaining the list. I think we will be better able to keep the list up to date. Will open an PR for this.
