### ISSUE TITLE
Add Yoursafe to the iDEAL issuers

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay-ingenico#7]
https://github.com/pronamic/wp-pronamic-pay-ingenico/blob/00a0f5a221e94eaee8dcaa12c8a31287dc9c0c45/src/OrderStandard/Gateway.php#L103-L128

https://www.ideal.nl/en/partners/issuers/

I currently don't see Yoursafe on https://availability.ideal.nl/ and https://support.legacy.worldline-solutions.com/nl/payment-methods/alternative-payment-methods/ideal.

- https://github.com/pronamic/wp-pronamic-pay-ingenico/issues/5

**Comment by rvdsteege** [comment]
Probably `BITSNL2A`, according to https://transaction.digiwallet.nl/ideal/getissuers?ver=4&format=json
