### ISSUE TITLE
Add support for `COMPLUS` parameter

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay-ingenico#9]
**English**
https://support.legacy.worldline-solutions.com/en/help/parameter-cookbook

Field name | Details | Input | Output | Format | Max Length | Example
-- | -- | -- | -- | -- | -- | --
`COM` | Order description — The com field is sometimes transmitted to the acquirer (depending on the acquirer), in order to be shown on the account statements of the merchant or the customer. | Yes | No | AN | 100 | Three telephone cards
`COMPLUS` | Field to submit a value you wish to receive back in the post sale request or output. `COMPLUS` is different from “com” in the sense that the `COMPLUS` field is longer, however, the `COMPLUS` info will not be shown in the back-office.Can be used to get back session info, order content or user info after the transaction. | Yes | Yes | AN | 1000 | Three telephone cards

**Dutch**
https://support.legacy.worldline-solutions.com/nl/help/parameter-cookbook

Veldnaam | Details | Input | Output | Format | Max. lengte | Voorbeeld
-- | -- | -- | -- | -- | -- | --
`COM` | Beschrijving van de bestelling — Het veld com wordt soms naar de acquirer verzonden (afhankelijk van de acquirer) om te worden weergegeven op het rekeninguittreksel van de handelaar of van de klant. | Ja | Nee | AN | 100 | Three telephone cards
`COMPLUS` | Veld voor de verzending van een waarde die u in het verzoek na verkoop of in de output wenst terug te krijgen. `COMPLUS` verschilt van com in de zin dat het veld `COMPLUS` langer is maar de informatie van `COMPLUS` wordt niet weergegeven in de backoffice. Kan worden gebruikt om na de transactie informatie terug te krijgen over de sessie de inhoud van de bestelling of de gebruiker. | Ja | Ja | AN | 1000 | Three telephone cards

---

I have no idea why they named this parameter `COM` and `COMPLUS`. Is it an abbreviation for "**C**ustomer **O**rder **M**essage"?

**Comment by rvdsteege** [comment]
Could maybe also have to with `communication` / `communicate`? I have no idea either… (couldn't find anything relevant online) 🤷‍♂️

**Comment by remcotolsma** [comment]
**ChatGPT** in Dutch:

> Ja, de parameter "COM" in de payment API van Ogone (ook bekend als Ingenico) staat voor "Communication". Het wordt gebruikt om een optioneel veld aan te duiden waarin je een aangepaste communicatie of een specifieke boodschap kunt opgeven die je wilt associëren met de betalingstransactie. Deze parameter biedt je de mogelijkheid om extra informatie te verstrekken die nuttig kan zijn voor jouw administratieve doeleinden of om specifieke instructies aan de betalingsverwerker door te geven.
> 
> Het gebruik van de "COM"-parameter stelt handelaren in staat om interne referenties, klantinformatie, bestelgegevens of andere relevante details aan een betalingstransactie toe te voegen. Deze informatie kan later worden opgenomen in rapporten of transactiegegevens die beschikbaar zijn via het Ogone/Ingenico-platform, waardoor het gemakkelijker wordt om betalingen te identificeren en te koppelen aan specifieke klanten of bestellingen.

---

> Hoewel de exacte betekenis van de "COM"-parameter niet expliciet wordt gespecificeerd door Ogone/Ingenico, kan het inderdaad worden geïnterpreteerd als "Customer Order Message" of een vergelijkbare term, afhankelijk van de context en het gebruiksscenario. Aangezien deze parameter wordt gebruikt om aangepaste communicatie of specifieke boodschappen aan betalingstransacties toe te voegen, kan het worden gebruikt om klantgerelateerde informatie, inclusief bestelberichten, te verzenden.
> 
> Het is echter belangrijk om op te merken dat de betekenis van de "COM"-parameter kan variëren, afhankelijk van de specifieke implementatie en configuratie van de betalingsgateway. Daarom is het altijd raadzaam om de documentatie of richtlijnen van Ogone/Ingenico te raadplegen voor de meest accurate en up-to-date informatie over de beschikbare parameters en hun betekenis in de context van hun payment API.
